// Self-host Google Fonts (Playfair Display + Manrope) as variable woff2,
// limited to the subsets we actually need:
//   latin      — base
//   latin-ext  — Romanian diacritics (ă â î ș ț)
//   cyrillic   — Russian
//
// Run:  npm run fonts
// Output: src/assets/fonts/*.woff2  +  src/styles/fonts.css
import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const FONTS_DIR = resolve(__dirname, '../src/assets/fonts')
const CSS_OUT = resolve(__dirname, '../src/styles/fonts.css')

// Pretend to be a modern browser so Google serves woff2 + variable fonts.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

const SOURCES = [
  {
    family: 'Playfair Display',
    url: 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..700&display=swap',
  },
  {
    family: 'Manrope',
    url: 'https://fonts.googleapis.com/css2?family=Manrope:wght@300..800&display=swap',
  },
]

const ALLOWED = new Set(['latin', 'latin-ext', 'cyrillic'])
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

async function run() {
  await mkdir(FONTS_DIR, { recursive: true })
  await mkdir(dirname(CSS_OUT), { recursive: true })
  let cssOut = `/* Auto-generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n`
  const seen = new Set()

  for (const src of SOURCES) {
    const res = await fetch(src.url, { headers: { 'User-Agent': UA } })
    if (!res.ok) throw new Error(`Failed to fetch CSS for ${src.family}: ${res.status}`)
    const css = await res.text()

    // Each face is preceded by a /* subset */ comment.
    const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g
    let m
    while ((m = re.exec(css)) !== null) {
      const subset = m[1]
      if (!ALLOWED.has(subset)) continue
      const block = m[2]
      const styleMatch = block.match(/font-style:\s*(\w+)/)
      const style = styleMatch ? styleMatch[1] : 'normal'
      const urlMatch = block.match(/src:\s*url\(([^)]+)\)/)
      if (!urlMatch) continue
      const woffUrl = urlMatch[1].replace(/["']/g, '')

      const fileName = `${slug(src.family)}-${style}-${subset}.woff2`
      if (!seen.has(fileName)) {
        seen.add(fileName)
        const bin = await fetch(woffUrl, { headers: { 'User-Agent': UA } })
        if (!bin.ok) throw new Error(`Failed to download ${woffUrl}`)
        const buf = Buffer.from(await bin.arrayBuffer())
        await writeFile(resolve(FONTS_DIR, fileName), buf)
        console.log(`  saved ${fileName} (${Math.round(buf.length / 1024)} KB)`)
      }

      const localBlock = block
        .replace(/src:\s*url\([^)]+\)/, `src: url(../assets/fonts/${fileName})`)
        .trim()
      cssOut += `\n/* ${src.family} — ${subset} (${style}) */\n@font-face {\n  ${localBlock}\n}\n`
    }
  }

  await writeFile(CSS_OUT, cssOut)
  console.log(`\nWrote ${CSS_OUT}`)
}

run().catch((e) => {
  console.error(e)
  process.exit(1)
})
